export const env = {
  port: parseInt(process.env.API_PORT || '4000', 10),
  host: process.env.API_HOST || '0.0.0.0',
  databaseUrl: process.env.DATABASE_URL || 'postgresql://bartr:bartr_dev_password@localhost:5432/bartr',
  redisUrl: process.env.REDIS_URL || 'redis://localhost:6379',
  jwtSecret: process.env.JWT_SECRET || 'bartr-dev-jwt-secret-change-in-production',
  jwtAccessExpiry: process.env.JWT_ACCESS_EXPIRY || '15m',
  jwtRefreshExpiry: process.env.JWT_REFRESH_EXPIRY || '7d',
  googleClientId: process.env.GOOGLE_CLIENT_ID || '',
  googleClientSecret: process.env.GOOGLE_CLIENT_SECRET || '',
  googleRedirectUri: process.env.GOOGLE_REDIRECT_URI || 'http://localhost/api/auth/google/callback',
  clientUrl: process.env.CLIENT_URL || 'http://localhost',
  minioEndpoint: process.env.MINIO_ENDPOINT || 'http://localhost:9000',
  minioAccessKey: process.env.MINIO_ROOT_USER || 'bartr',
  minioSecretKey: process.env.MINIO_ROOT_PASSWORD || 'bartr_dev_password',
  minioBucket: process.env.MINIO_BUCKET || 'listing-images',
} as const;
