/** ISO 3166-1 alpha-2 country list with flag emojis. */

export interface Country {
  code: string;
  name: string;
  flag: string;
}

/** Derive flag emoji from a 2-letter ISO country code (regional indicator symbols). */
function flag(code: string): string {
  return String.fromCodePoint(
    ...code.toUpperCase().split('').map((c) => 0x1f1e6 + c.charCodeAt(0) - 65),
  );
}

function c(code: string, name: string): Country {
  return { code, name, flag: flag(code) };
}

export const COUNTRIES: Country[] = [
  c('AF', 'Afghanistan'),
  c('AL', 'Albania'),
  c('DZ', 'Algeria'),
  c('AD', 'Andorra'),
  c('AO', 'Angola'),
  c('AG', 'Antigua and Barbuda'),
  c('AR', 'Argentina'),
  c('AM', 'Armenia'),
  c('AU', 'Australia'),
  c('AT', 'Austria'),
  c('AZ', 'Azerbaijan'),
  c('BS', 'Bahamas'),
  c('BH', 'Bahrain'),
  c('BD', 'Bangladesh'),
  c('BB', 'Barbados'),
  c('BY', 'Belarus'),
  c('BE', 'Belgium'),
  c('BZ', 'Belize'),
  c('BJ', 'Benin'),
  c('BT', 'Bhutan'),
  c('BO', 'Bolivia'),
  c('BA', 'Bosnia and Herzegovina'),
  c('BW', 'Botswana'),
  c('BR', 'Brazil'),
  c('BN', 'Brunei'),
  c('BG', 'Bulgaria'),
  c('BF', 'Burkina Faso'),
  c('BI', 'Burundi'),
  c('CV', 'Cabo Verde'),
  c('KH', 'Cambodia'),
  c('CM', 'Cameroon'),
  c('CA', 'Canada'),
  c('CF', 'Central African Republic'),
  c('TD', 'Chad'),
  c('CL', 'Chile'),
  c('CN', 'China'),
  c('CO', 'Colombia'),
  c('KM', 'Comoros'),
  c('CG', 'Congo'),
  c('CD', 'Congo (DRC)'),
  c('CR', 'Costa Rica'),
  c('CI', "Cote d'Ivoire"),
  c('HR', 'Croatia'),
  c('CU', 'Cuba'),
  c('CY', 'Cyprus'),
  c('CZ', 'Czechia'),
  c('DK', 'Denmark'),
  c('DJ', 'Djibouti'),
  c('DM', 'Dominica'),
  c('DO', 'Dominican Republic'),
  c('EC', 'Ecuador'),
  c('EG', 'Egypt'),
  c('SV', 'El Salvador'),
  c('GQ', 'Equatorial Guinea'),
  c('ER', 'Eritrea'),
  c('EE', 'Estonia'),
  c('SZ', 'Eswatini'),
  c('ET', 'Ethiopia'),
  c('FJ', 'Fiji'),
  c('FI', 'Finland'),
  c('FR', 'France'),
  c('GA', 'Gabon'),
  c('GM', 'Gambia'),
  c('GE', 'Georgia'),
  c('DE', 'Germany'),
  c('GH', 'Ghana'),
  c('GR', 'Greece'),
  c('GD', 'Grenada'),
  c('GT', 'Guatemala'),
  c('GN', 'Guinea'),
  c('GW', 'Guinea-Bissau'),
  c('GY', 'Guyana'),
  c('HT', 'Haiti'),
  c('HN', 'Honduras'),
  c('HU', 'Hungary'),
  c('IS', 'Iceland'),
  c('IN', 'India'),
  c('ID', 'Indonesia'),
  c('IR', 'Iran'),
  c('IQ', 'Iraq'),
  c('IE', 'Ireland'),
  c('IL', 'Israel'),
  c('IT', 'Italy'),
  c('JM', 'Jamaica'),
  c('JP', 'Japan'),
  c('JO', 'Jordan'),
  c('KZ', 'Kazakhstan'),
  c('KE', 'Kenya'),
  c('KI', 'Kiribati'),
  c('KP', 'North Korea'),
  c('KR', 'South Korea'),
  c('KW', 'Kuwait'),
  c('KG', 'Kyrgyzstan'),
  c('LA', 'Laos'),
  c('LV', 'Latvia'),
  c('LB', 'Lebanon'),
  c('LS', 'Lesotho'),
  c('LR', 'Liberia'),
  c('LY', 'Libya'),
  c('LI', 'Liechtenstein'),
  c('LT', 'Lithuania'),
  c('LU', 'Luxembourg'),
  c('MG', 'Madagascar'),
  c('MW', 'Malawi'),
  c('MY', 'Malaysia'),
  c('MV', 'Maldives'),
  c('ML', 'Mali'),
  c('MT', 'Malta'),
  c('MH', 'Marshall Islands'),
  c('MR', 'Mauritania'),
  c('MU', 'Mauritius'),
  c('MX', 'Mexico'),
  c('FM', 'Micronesia'),
  c('MD', 'Moldova'),
  c('MC', 'Monaco'),
  c('MN', 'Mongolia'),
  c('ME', 'Montenegro'),
  c('MA', 'Morocco'),
  c('MZ', 'Mozambique'),
  c('MM', 'Myanmar'),
  c('NA', 'Namibia'),
  c('NR', 'Nauru'),
  c('NP', 'Nepal'),
  c('NL', 'Netherlands'),
  c('NZ', 'New Zealand'),
  c('NI', 'Nicaragua'),
  c('NE', 'Niger'),
  c('NG', 'Nigeria'),
  c('MK', 'North Macedonia'),
  c('NO', 'Norway'),
  c('OM', 'Oman'),
  c('PK', 'Pakistan'),
  c('PW', 'Palau'),
  c('PA', 'Panama'),
  c('PG', 'Papua New Guinea'),
  c('PY', 'Paraguay'),
  c('PE', 'Peru'),
  c('PH', 'Philippines'),
  c('PL', 'Poland'),
  c('PT', 'Portugal'),
  c('QA', 'Qatar'),
  c('RO', 'Romania'),
  c('RU', 'Russia'),
  c('RW', 'Rwanda'),
  c('KN', 'Saint Kitts and Nevis'),
  c('LC', 'Saint Lucia'),
  c('VC', 'Saint Vincent and the Grenadines'),
  c('WS', 'Samoa'),
  c('SM', 'San Marino'),
  c('ST', 'Sao Tome and Principe'),
  c('SA', 'Saudi Arabia'),
  c('SN', 'Senegal'),
  c('RS', 'Serbia'),
  c('SC', 'Seychelles'),
  c('SL', 'Sierra Leone'),
  c('SG', 'Singapore'),
  c('SK', 'Slovakia'),
  c('SI', 'Slovenia'),
  c('SB', 'Solomon Islands'),
  c('SO', 'Somalia'),
  c('ZA', 'South Africa'),
  c('SS', 'South Sudan'),
  c('ES', 'Spain'),
  c('LK', 'Sri Lanka'),
  c('SD', 'Sudan'),
  c('SR', 'Suriname'),
  c('SE', 'Sweden'),
  c('CH', 'Switzerland'),
  c('SY', 'Syria'),
  c('TW', 'Taiwan'),
  c('TJ', 'Tajikistan'),
  c('TZ', 'Tanzania'),
  c('TH', 'Thailand'),
  c('TL', 'Timor-Leste'),
  c('TG', 'Togo'),
  c('TO', 'Tonga'),
  c('TT', 'Trinidad and Tobago'),
  c('TN', 'Tunisia'),
  c('TR', 'Turkey'),
  c('TM', 'Turkmenistan'),
  c('TV', 'Tuvalu'),
  c('UG', 'Uganda'),
  c('UA', 'Ukraine'),
  c('AE', 'United Arab Emirates'),
  c('GB', 'United Kingdom'),
  c('US', 'United States'),
  c('UY', 'Uruguay'),
  c('UZ', 'Uzbekistan'),
  c('VU', 'Vanuatu'),
  c('VA', 'Vatican City'),
  c('VE', 'Venezuela'),
  c('VN', 'Vietnam'),
  c('YE', 'Yemen'),
  c('ZM', 'Zambia'),
  c('ZW', 'Zimbabwe'),
];

/** Map of country code → Country for quick lookup. */
export const COUNTRY_MAP = new Map(COUNTRIES.map((c) => [c.code, c]));

/** Get flag emoji for a country code, or empty string if unknown. */
export function getCountryFlag(code: string | null | undefined): string {
  if (!code) return '';
  return COUNTRY_MAP.get(code.toUpperCase())?.flag ?? '';
}

/** Get country name for a country code, or empty string if unknown. */
export function getCountryName(code: string | null | undefined): string {
  if (!code) return '';
  return COUNTRY_MAP.get(code.toUpperCase())?.name ?? '';
}
