import type { Pool } from 'pg';

// ── Adjectives (≤5 chars, ~400 words) ─────────────────────────────────────
const ADJECTIVES = [
  'Arid', 'Avid', 'Aged', 'Able', 'Aced',
  'Bare', 'Bold', 'Calm', 'Cold', 'Cool',
  'Cozy', 'Crisp', 'Cyan', 'Dark', 'Damp',
  'Dead', 'Deep', 'Dire', 'Dull', 'Dual',
  'Dusk', 'Dusty', 'Ebon', 'Edgy', 'Epic',
  'Even', 'Eerie', 'Faint', 'Fair', 'Fast',
  'Fell', 'Fiery', 'Fine', 'Firm', 'Fizzy',
  'Flat', 'Fleet', 'Fluid', 'Fond', 'Free',
  'Foul', 'Frozen', 'Full', 'Fuzzy', 'Grim',
  'Gloom', 'Glow', 'Gold', 'Gone', 'Good',
  'Grand', 'Grave', 'Gray', 'Grim', 'Gritty',
  'Hard', 'Hazy', 'High', 'Holy', 'Hot',
  'Huge', 'Icy', 'Idle', 'Inky', 'Iron',
  'Jade', 'Just', 'Keen', 'Kind', 'Lean',
  'Late', 'Lazy', 'Lofty', 'Lone', 'Long',
  'Lost', 'Loud', 'Low', 'Lucid', 'Lunar',
  'Lush', 'Mad', 'Matte', 'Meek', 'Mild',
  'Mint', 'Misty', 'Mono', 'Murky', 'Mute',
  'Mystic', 'Neon', 'New', 'Nimble', 'Noir',
  'Null', 'Odd', 'Opal', 'Open', 'Outer',
  'Pale', 'Plain', 'Polar', 'Prime', 'Pure',
  'Quick', 'Quiet', 'Rare', 'Raw', 'Real',
  'Rich', 'Rigid', 'Rosy', 'Rough', 'Royal',
  'Rogue', 'Runic', 'Rusty', 'Safe', 'Sage',
  'Sandy', 'Sharp', 'Sheer', 'Shy', 'Sleek',
  'Slim', 'Slow', 'Smart', 'Smoky', 'Snowy',
  'Soft', 'Solar', 'Solid', 'Sonic', 'Spare',
  'Stark', 'Steel', 'Steep', 'Stern', 'Stiff',
  'Still', 'Stone', 'Storm', 'Stray', 'Sure',
  'Swift', 'Tame', 'Taut', 'Teal', 'Thin',
  'Tidy', 'Torn', 'True', 'Terse', 'Tense',
  'Tiny', 'Toxic', 'Ultra', 'Urban', 'Vast',
  'Vivid', 'Void', 'Warm', 'Wavy', 'Wiry',
  'Wise', 'Wild', 'Worn', 'Wry', 'Zero',
  'Zeal', 'Zinc', 'Zany', 'Aced', 'Adept',
  'Agile', 'Aloft', 'Amber', 'Ample', 'Angst',
  'Apart', 'Aptic', 'Ardent', 'Ashen', 'Askew',
  'Astral', 'Atilt', 'Awake', 'Awful', 'Azure',
  'Balmy', 'Bared', 'Basalt', 'Beryl', 'Black',
  'Blade', 'Bleak', 'Blunt', 'Brash', 'Brave',
  'Brisk', 'Broad', 'Brute', 'Burnt', 'Caged',
  'Carve', 'Cedar', 'Chill', 'Civic', 'Civil',
  'Clad', 'Cleft', 'Cloaked', 'Close', 'Coil',
  'Coral', 'Coven', 'Covert', 'Cracked', 'Crane',
  'Crisp', 'Cross', 'Crude', 'Crypt', 'Cubic',
  'Curled', 'Dense', 'Depot', 'Drawn', 'Drift',
  'Druid', 'Dry', 'Dusky', 'Dyed', 'Eagle',
  'Early', 'Eased', 'Elder', 'Ember', 'Empty',
  'Exact', 'Exiled', 'Faded', 'Feral', 'Ferric',
  'Fetch', 'Fixed', 'Flash', 'Fleet', 'Float',
  'Flint', 'Flux', 'Foggy', 'Forge', 'Forged',
  'Frail', 'Frank', 'Fresh', 'Frost', 'Gaunt',
  'Ghost', 'Giant', 'Giddy', 'Gilt', 'Glacial',
  'Glare', 'Glass', 'Glint', 'Gloom', 'Gloss',
  'Gnarly', 'Gravel', 'Green', 'Grim', 'Gross',
  'Grove', 'Guile', 'Gulf', 'Harsh', 'Haven',
  'Heavy', 'Helix', 'Hidden', 'Hoary', 'Horned',
  'Howl', 'Humid', 'Hyper', 'Imbued', 'Inner',
  'Inert', 'Inter', 'Irate', 'Jagged', 'Jolted',
  'Jumpy', 'Kalic', 'Krypt', 'Lanky', 'Large',
  'Laser', 'Latent', 'Leaden', 'Lithe', 'Livid',
  'Loose', 'Lumpy', 'Lurid', 'Lusty', 'Magic',
  'Major', 'Mantle', 'Marble', 'Mired', 'Modal',
  'Molten', 'Mossy', 'Muddy', 'Naked', 'Narrow',
  'Native', 'Netted', 'Noble', 'Nomad', 'Norsk',
  'Noted', 'Oblong', 'Ochre', 'Olive', 'Onyx',
  'Optic', 'Orbit', 'Oxide', 'Pagan', 'Patchy',
  'Penal', 'Phase', 'Pixel', 'Pitted', 'Pivot',
  'Plaid', 'Plasma', 'Plumed', 'Plunge', 'Potent',
  'Primal', 'Prism', 'Prone', 'Proxy', 'Proud',
  'Pumice', 'Quartz', 'Quasar', 'Quirky', 'Ragged',
  'Raven', 'Razed', 'Regal', 'Remote', 'Renown',
  'Resin', 'Ridge', 'Ringed', 'Risen', 'Rivet',
  'Rocky', 'Rune', 'Runed', 'Runic', 'Sacred',
  'Salt', 'Sable', 'Scaled', 'Scarce', 'Seared',
  'Serene', 'Shaded', 'Shard', 'Sheer', 'Shroud',
  'Siege', 'Sigil', 'Signal', 'Silent', 'Silver',
  'Sinew', 'Sixth', 'Skewed', 'Slate', 'Slick',
  'Spare', 'Spark', 'Spire', 'Split', 'Stale',
  'Stamp', 'Static', 'Stoic', 'Stout', 'Strand',
  'Strewn', 'Strict', 'Strife', 'Strix', 'Strong',
  'Stunned', 'Subtle', 'Summit', 'Surge', 'Swarm',
  'Swept', 'Talon', 'Tangled', 'Tawny', 'Tempered',
  'Thorn', 'Thrice', 'Tidal', 'Tiger', 'Token',
  'Totem', 'Trace', 'Triad', 'Triune', 'Tundra',
  'Turbid', 'Twin', 'Typed', 'Umbra', 'Unlit',
  'Unseen', 'Upward', 'Vaned', 'Vapor', 'Veiled',
  'Vexed', 'Virid', 'Viral', 'Visage', 'Visual',
  'Vitreous', 'Volant', 'Walled', 'Warped', 'Wired',
  'Wolven', 'Woven', 'Wraith', 'Wrought', 'Xenon',
];

// ── Noun bank 1 — materials / elements / forces (≤5 chars) ────────────────
const NOUNS1 = [
  'Acid', 'Aeon', 'Aero', 'Alloy', 'Alter',
  'Amber', 'Ambit', 'Anion', 'Anvil', 'Apex',
  'Argon', 'Arson', 'Arxon', 'Ashen', 'Aster',
  'Atlas', 'Atom', 'Aura', 'Axle', 'Azure',
  'Basalt', 'Beam', 'Blaze', 'Bloom', 'Bolt',
  'Bone', 'Brine', 'Brume', 'Burn', 'Byte',
  'Cable', 'Carve', 'Chalk', 'Chaos', 'Char',
  'Chasm', 'Chill', 'Chord', 'Cinch', 'Cinder',
  'Clay', 'Coal', 'Coil', 'Coral', 'Core',
  'Cosm', 'Craft', 'Creek', 'Crest', 'Crisp',
  'Crown', 'Crust', 'Crux', 'Crypt', 'Crystal',
  'Cycle', 'Delta', 'Depth', 'Dew', 'Dirge',
  'Drift', 'Drone', 'Dune', 'Dusk', 'Dust',
  'Dynamo', 'Ebb', 'Edge', 'Elegy', 'Ember',
  'Epoch', 'Ether', 'Event', 'Exhaust', 'Exon',
  'Fault', 'Ferro', 'Field', 'Filament', 'Flare',
  'Flash', 'Flint', 'Flood', 'Flow', 'Flux',
  'Foam', 'Focus', 'Forge', 'Frost', 'Fuel',
  'Fume', 'Fused', 'Gale', 'Gamma', 'Gash',
  'Gas', 'Gate', 'Gavel', 'Gel', 'Gild',
  'Glair', 'Glare', 'Glass', 'Glow', 'Glyph',
  'Grain', 'Grant', 'Gravel', 'Grid', 'Grime',
  'Grind', 'Groan', 'Grove', 'Gulf', 'Halo',
  'Haze', 'Heat', 'Helix', 'Horn', 'Hull',
  'Hum', 'Hydro', 'Ignis', 'Ingot', 'Ionic',
  'Iron', 'Ivory', 'Jade', 'Jolt', 'Kelp',
  'Klang', 'Knell', 'Lava', 'Layer', 'Lead',
  'Ley', 'Light', 'Lime', 'Lith', 'Lode',
  'Loess', 'Lumen', 'Magma', 'Mana', 'Marble',
  'Marsh', 'Meld', 'Mesh', 'Metal', 'Mist',
  'Moat', 'Molt', 'Mote', 'Mud', 'Nadir',
  'Nexus', 'Nimbus', 'Nitro', 'Node', 'Noise',
  'Nova', 'Null', 'Obsid', 'Ocean', 'Ochre',
  'Onyx', 'Orbit', 'Ore', 'Oxide', 'Ozone',
  'Patch', 'Peat', 'Phase', 'Plasm', 'Plate',
  'Plume', 'Polar', 'Pulse', 'Pyro', 'Quake',
  'Quark', 'Quartz', 'Rack', 'Radix', 'Rain',
  'Realm', 'Resin', 'Ridge', 'Rift', 'Rune',
  'Rust', 'Salt', 'Sand', 'Scald', 'Scale',
  'Seam', 'Shard', 'Sheen', 'Shell', 'Silt',
  'Slag', 'Slate', 'Sleet', 'Smoke', 'Smolt',
  'Snow', 'Solar', 'Sonar', 'Soot', 'Sound',
  'Spark', 'Spore', 'Spray', 'Squall', 'Stack',
  'Steam', 'Steel', 'Stone', 'Storm', 'Strap',
  'Straw', 'Stream', 'Surge', 'Swamp', 'Synth',
  'Thorn', 'Tide', 'Timbre', 'Tine', 'Titan',
  'Torch', 'Toxin', 'Trace', 'Trail', 'Trench',
  'Trial', 'Tuft', 'Tundra', 'Vapor', 'Vein',
  'Vitre', 'Void', 'Volt', 'Vortex', 'Waste',
  'Water', 'Wave', 'Weld', 'Wind', 'Wire',
  'Wood', 'Xeno', 'Xenon', 'Yoke', 'Zeal',
  'Zinc', 'Zone', 'Sable', 'Raze', 'Seraph',
  'Sigma', 'Slope', 'Smear', 'Smelt', 'Smite',
  'Sonic', 'Spall', 'Spine', 'Split', 'Sprue',
  'Strut', 'Stung', 'Styx', 'Swath', 'Sweep',
  'Swift', 'Talon', 'Taper', 'Tarry', 'Tawny',
  'Tempo', 'Tenor', 'Terra', 'Tidal', 'Topaz',
  'Totem', 'Triac', 'Triad', 'Trine', 'Trode',
  'Troll', 'Tropo', 'Truth', 'Tuner', 'Turbo',
  'Twill', 'Twist', 'Umbra', 'Unify', 'Unity',
  'Valor', 'Valve', 'Vapor', 'Vaunt', 'Velix',
  'Virid', 'Visor', 'Volta', 'Vrent', 'Wane',
  'Warp', 'Weave', 'Whirl', 'Wisp', 'Wrack',
  'Wrath', 'Wreck', 'Xenith', 'Xylem', 'Yield',
  'Zenith', 'Zephyr', 'Zonal', 'Drawn', 'Drift',
  'Epoch', 'Exon', 'Flax', 'Glyph', 'Grant',
  'Groan', 'Haul', 'Hydra', 'Ingot', 'Kiln',
  'Knell', 'Latch', 'Loam', 'Lorry', 'Lustre',
  'Lyric', 'Macro', 'Magnet', 'Manor', 'Marsh',
  'Micro', 'Mire', 'Mono', 'Moult', 'Murk',
  'Myrrh', 'Nebula', 'Notch', 'Nymph', 'Orb',
  'Parch', 'Petal', 'Pivot', 'Pixel', 'Plait',
  'Plank', 'Plinth', 'Plod', 'Plume', 'Point',
];

// ── Noun bank 2 — animals / creatures / objects (≤5 chars) ────────────────
const NOUNS2 = [
  'Adder', 'Aeon', 'Agama', 'Agave', 'Agent',
  'Algae', 'Alga', 'Aloe', 'Alpax', 'Anvil',
  'Ape', 'Asp', 'Auk', 'Avian', 'Axe',
  'Bison', 'Blade', 'Blaze', 'Blight', 'Boar',
  'Bobcat', 'Bolt', 'Booby', 'Buck', 'Bug',
  'Bull', 'Burro', 'Caiman', 'Cape', 'Carp',
  'Cat', 'Chub', 'Clam', 'Claw', 'Club',
  'Cobra', 'Cock', 'Cod', 'Condor', 'Coney',
  'Conger', 'Cord', 'Cougar', 'Crane', 'Croc',
  'Crow', 'Cub', 'Culex', 'Curio', 'Dace',
  'Dart', 'Deer', 'Dingo', 'Dirk', 'Divet',
  'Dodo', 'Dog', 'Dory', 'Dove', 'Drake',
  'Drone', 'Duck', 'Eagle', 'Egret', 'Eland',
  'Elk', 'Emu', 'Fawn', 'Feral', 'Fetch',
  'Finch', 'Fish', 'Flask', 'Flea', 'Flint',
  'Fly', 'Foal', 'Fox', 'Frog', 'Gator',
  'Gaur', 'Gecko', 'Genet', 'Gila', 'Gnu',
  'Goat', 'Grebe', 'Grub', 'Gull', 'Hare',
  'Hawk', 'Heron', 'Hind', 'Hippo', 'Hive',
  'Hook', 'Horn', 'Hornet', 'Hound', 'Hydra',
  'Hyena', 'Ibex', 'Ibis', 'Imp', 'Jackal',
  'Jay', 'Kea', 'Kite', 'Kiwi', 'Knot',
  'Kudu', 'Lance', 'Lark', 'Leech', 'Lemur',
  'Liger', 'Lion', 'Loon', 'Lure', 'Lynx',
  'Mace', 'Mamba', 'Mink', 'Mite', 'Mole',
  'Moose', 'Moth', 'Mouse', 'Mule', 'Mutt',
  'Narc', 'Newt', 'Nymph', 'Okapi', 'Oryx',
  'Osprey', 'Otter', 'Owl', 'Ox', 'Panda',
  'Panther', 'Perch', 'Pike', 'Pilot', 'Pipit',
  'Pony', 'Porcupine', 'Puma', 'Quail', 'Quoll',
  'Ram', 'Raptor', 'Rat', 'Raven', 'Ray',
  'Rhino', 'Rook', 'Ruff', 'Sable', 'Saiga',
  'Sambar', 'Scamp', 'Scout', 'Seal', 'Serval',
  'Shark', 'Shrew', 'Skink', 'Skua', 'Slug',
  'Smew', 'Snail', 'Snake', 'Snipe', 'Spade',
  'Spear', 'Spawn', 'Spur', 'Staff', 'Stag',
  'Stake', 'Stoat', 'Stork', 'Strap', 'Swan',
  'Tapir', 'Teal', 'Tern', 'Tiger', 'Toad',
  'Token', 'Trout', 'Tuna', 'Tusk', 'Viper',
  'Vole', 'Vulture', 'Wapiti', 'Wasp', 'Whelk',
  'Wolf', 'Wombat', 'Wren', 'Yak', 'Zebra',
  'Zibet', 'Zorilla', 'Axon', 'Badge', 'Barb',
  'Barge', 'Baron', 'Baton', 'Beak', 'Beast',
  'Berth', 'Bilge', 'Birch', 'Blight', 'Bluff',
  'Board', 'Brace', 'Brand', 'Brant', 'Brash',
  'Brood', 'Brunt', 'Brush', 'Bunt', 'Buoy',
  'Burr', 'Cache', 'Cairn', 'Canid', 'Canon',
  'Cavy', 'Celt', 'Chad', 'Chain', 'Chomp',
  'Chuff', 'Chunk', 'Cleft', 'Clump', 'Clutch',
  'Comet', 'Conch', 'Corse', 'Crest', 'Crook',
  'Cross', 'Croup', 'Crush', 'Culm', 'Cusp',
  'Dagger', 'Dale', 'Dank', 'Dapple', 'Dirge',
  'Disk', 'Divet', 'Dolmen', 'Draft', 'Drape',
  'Dray', 'Dread', 'Drew', 'Drift', 'Drill',
  'Drub', 'Drum', 'Dune', 'Duvet', 'Dwarf',
  'Fang', 'Fern', 'Fiber', 'Firth', 'Flag',
  'Flair', 'Flank', 'Flare', 'Flock', 'Floe',
  'Floss', 'Fluke', 'Flume', 'Flurry', 'Flute',
  'Frame', 'Frond', 'Froth', 'Frump', 'Fungi',
  'Fyrd', 'Gavel', 'Girth', 'Gnome', 'Grail',
  'Grime', 'Gripe', 'Grout', 'Guard', 'Guild',
  'Guise', 'Gulch', 'Gust', 'Gyre', 'Haft',
  'Hank', 'Hasp', 'Haul', 'Haven', 'Hazel',
  'Helm', 'Hemp', 'Hilt', 'Hinge', 'Hoard',
  'Holst', 'Hulk', 'Husk', 'Hutch', 'Index',
  'Inset', 'Joust', 'Keel', 'Keep', 'Kelp',
  'Kestrel', 'Knave', 'Knob', 'Knoll', 'Latch',
  'Lath', 'Ledge', 'Leech', 'Liege', 'Lilt',
  'Limb', 'Lodge', 'Loft', 'Lore', 'Lump',
  'Lurk', 'Mast', 'Match', 'Maul', 'Maze',
  'Mesh', 'Moil', 'Mold', 'Mote', 'Mound',
  'Mount', 'Mural', 'Notch', 'Nozzle', 'Oaken',
  'Obelisk', 'Pact', 'Paean', 'Pall', 'Parry',
  'Patch', 'Pearl', 'Peel', 'Pelt', 'Perch',
  'Pile', 'Pinch', 'Pitch', 'Plane', 'Plank',
  'Plate', 'Plume', 'Pouch', 'Prow', 'Prune',
  'Puck', 'Purse', 'Queue', 'Quill', 'Rabble',
  'Rack', 'Rampart', 'Rasp', 'Reed', 'Reef',
  'Reign', 'Relic', 'Rend', 'Rile', 'Rivet',
  'Rope', 'Roost', 'Roue', 'Rubble', 'Rung',
];

// ── Helpers ────────────────────────────────────────────────────────────────

function randomItem<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

function randomSuffix(): number {
  return Math.floor(Math.random() * 100); // 0–99
}

export function generateNickname(): string {
  return `${randomItem(ADJECTIVES)}${randomItem(NOUNS1)}${randomItem(NOUNS2)}${randomSuffix()}`;
}

/**
 * Generate a nickname guaranteed to be unique in the DB.
 * Tries up to 10 random combinations, then falls back to incrementing the suffix.
 */
export async function generateUniqueNickname(pg: Pool): Promise<string> {
  for (let i = 0; i < 10; i++) {
    const candidate = generateNickname();
    const { rows } = await pg.query('SELECT 1 FROM users WHERE nickname = $1', [candidate]);
    if (rows.length === 0) return candidate;
  }

  // Fallback: fix adj+noun1+noun2, walk the suffix space then beyond
  const adj = randomItem(ADJECTIVES);
  const n1 = randomItem(NOUNS1);
  const n2 = randomItem(NOUNS2);
  for (let i = 0; i < 10000; i++) {
    const candidate = `${adj}${n1}${n2}${i}`;
    const { rows } = await pg.query('SELECT 1 FROM users WHERE nickname = $1', [candidate]);
    if (rows.length === 0) return candidate;
  }

  return `${adj}${n1}${n2}${Date.now()}`;
}

export function totalCombinations(): number {
  return ADJECTIVES.length * NOUNS1.length * NOUNS2.length * 100;
}
